# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

jobs:
  - template: templates/sonar-cloud-analysis-template.yml
    parameters:
      projectKey: cultwines_portal-web-app
      projectName: portal-web-app
