export enum GQLMessageKeys {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  UNABLE_TO_LOGIN = 'UNABLE_TO_LOGIN',
  ACCOUNT_FOUND_FAIL_SECURITY_CHECKS = 'ACCOUNT_FOUND_FAIL_SECURITY_CHECKS',

  FAIL_TO_LOGIN_AS_STAFF = 'FAIL_TO_LOGIN_AS_STAFF',
  UNABLE_TO_RESET_PASSWORD = 'UNABLE_TO_RESET_PASSWORD',
  PASSWORD_RESET_EMAIL_SENT = 'PASSWORD_RESET_EMAIL_SENT',
  PASSWORD_RESET_UNABLE_TO_FIND_ACCOUNT = 'PASSWORD_RESET_UNABLE_TO_FIND_ACCOUNT',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INVALID_LOGIN_DETAIL = 'INVALID_LOGIN_DETAIL',
  UNKNOWN_EMAIL_ERROR = 'UNKNOWN_EMAIL_ERROR',
  EMAIL_SENDER_DISABLED = 'EMAIL_SENDER_DISABLED',
  UNABLE_TO_SEND_EMAIL = 'UNABLE_TO_SEND_EMAIL',
  PASSWORD_ERROR = 'PASSWORD_ERROR',
  REGISTRATION_REQUIRE_FIELDS = 'REGISTRATION_REQUIRE_FIELDS',
  REGISTRATION_ERROR = 'REGISTRATION_ERROR',
  UNABLE_TO_CREATE_USER = 'UNABLE_TO_CREATE_USER',
  EMAIL_ALREADY_EXIST = 'EMAIL_ALREADY_EXIST',
  AUTO_LOGIN_USER = 'AUTO_LOGIN_USER',

  ACTIVATION_TOKEN = 'ACTIVATION_TOKEN',
  ACTIVATION_CODE_SENT = 'ACTIVATION_CODE_SENT',
  ACTIVATION_CODE_UNABLE_TO_FIND_ACCOUNT = 'ACTIVATION_CODE_UNABLE_TO_FIND_ACCOUNT',
  ACTIVATE_ACCOUNT_FAIL = 'ACTIVATE_ACCOUNT_FAIL',
  ACCOUNT_ACTIVATED = 'ACCOUNT_ACTIVATED',
  ACCOUNT_ACTIVATION_REQUIRED = 'ACCOUNT_ACTIVATION_REQUIRED',
  ACCOUNT_ACTIVATION_TOKEN_NOT_MATCH = 'ACCOUNT_ACTIVATION_TOKEN_NOT_MATCH',
  ACCOUNT_ACTIVATION_TOKEN_ERROR = 'ACCOUNT_ACTIVATION_TOKEN_ERROR',

  INVALID_PASSCODE = 'INVALID_PASSCODE',
  LOGIN_SUCCESSFULLY = 'LOGIN_SUCCESSFULLY',
  LOGIN_REQUIRED = 'LOGIN_REQUIRED',

  GENERATE_NEW_ACTIVATION_CODE = 'GENERATE_NEW_ACTIVATION_CODE',

  PASSWORD_CHANGE_REQUIRED = 'PASSWORD_CHANGE_REQUIRED',
}
